@url=http://localhost:8000/api
@player = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmI2MzI0OTY5NTc5NTNjNDU4MWZhZiIsImVtYWlsIjoibWVsdmluZ2FuMjgxMUBnbWFpbC5jb20iLCJuYW1lIjoiTWVsdmluIiwiYXZhdGFyIjoiLy93d3cuZ3JhdmF0YXIuY29tL2F2YXRhci9kYmM4Y2NlM2NhMTQzZjhlMmYyYzliMjU3NDY1YjAxYz9zPTIwMCZyPXBnJmQ9bW0iLCJpYXQiOjE2MzAzOTY1MjAsImV4cCI6MTYzMDQwMDEyMH0.dkK03lDWtrbq4vZaNQtM1DYagg4IkAEV9XZtP8q1lSY

### 1. Users
GET {{url}}/users/test HTTP/1.1
Content-type:application/json

###1. Get current user
GET  {{url}}/users/current HTTP/1.1
Content-Type:application/json
Authorization:Bearer {{player}}

### 1.Register new user
POST {{url}}/users/register HTTP/1.1
Content-Type:application/json

{
    "name":"May Doe",
    "email":"may@email.com",
    "password":"123456",
    "password2":"123456"

}


###1.Login user
POST {{url}}/users/login HTTP/1.1
Content-Type: application/json

{
    "email":"melvingan2811@gmail.com",
    "password":"123456"
}



###2.Profile
GET {{url}}/profile/test HTTP/1.1
Content-type:application/json

###2.Get current user profile
GET  {{url}}/profile HTTP/1.1
Content-Type:application/json
Authorization:Bearer {{player}}

###2.Get all user profile
GET  {{url}}/profile/all HTTP/1.1
Content-Type:application/json

###2.Get current user profile by handle
GET  {{url}}/profile/handle/johndoe HTTP/1.1
Content-Type:application/json

###2.Get current user profile by id
GET  {{url}}/profile/user/612b84d6b36622a1ee8582fesss HTTP/1.1
Content-Type:application/json

###2.Create new profile / edit new profile
POST  {{url}}/profile HTTP/1.1
Content-Type:application/json
Authorization:Bearer {{player}}

{
    "handle":"maydoe",
    "skills":"HTML,CSS,Javascript,PHP,React,Python,Express,NodeJs,Wordpress",
    "status":"Developer",
    "company":"dotcom",
    "website":"www.dotcom.com"
    
}

###2.Create new experience 
POST  {{url}}/profile/experience HTTP/1.1
Content-Type:application/json
Authorization:Bearer {{player}}

{
    "title":" developer",
    "company":"ABCD Company",
    "from":"2020",
    "to":"2021"
    
    
}

### 2.Create new education
POST  {{url}}/profile/education HTTP/1.1
Content-Type:application/json
Authorization:Bearer {{player}}

{
    "school":"ABC school",
    "degree":"Bachelors",
    "from":"2020",
    "to":"2021",
    "description":"Business information systems",
    "fieldofstudy":"Computer science"
    
}

### 2.Delete experience
DELETE  {{url}}/profile/experience/612dd4a9b97d1ee967ee63d5 HTTP/1.1
Content-Type:application/json
Authorization:Bearer {{player}}


### 2.Delete education
DELETE  {{url}}/profile/education/612cf7e6bc539e63b3e91b535 HTTP/1.1
Content-Type:application/json
Authorization:Bearer {{player}}

### 2.Delete user and profile
DELETE  {{url}}/profile HTTP/1.1
Content-Type:application/json
Authorization:Bearer {{player}}

###3.Posts
GET {{url}}/posts/test HTTP/1.1
Content-type:application/json

###3.Get all post
GET {{url}}/posts/ HTTP/1.1
Content-type:application/json

###3.Get post by id
GET {{url}}/posts/612de3a1a49ba8b12b91be98 HTTP/1.1
Content-type:application/json

###3.Create post
POST {{url}}/posts/ HTTP/1.1
Content-type:application/json
Authorization:Bearer {{player}}

{
    "text":"This is a test",
    "name":"John"
    

}

###3.Delete post BY ID
DELETE {{url}}/posts/612de3a1a49ba8b12b91be98 HTTP/1.1
Content-type:application/json
Authorization:Bearer {{player}}
