@url=http://localhost:8000/api
@player =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmI4NGQ2YjM2NjIyYTFlZTg1ODJmZSIsImVtYWlsIjoiam9obkBlbWFpbC5jb20iLCJuYW1lIjoiSm9obiBEb2UiLCJhdmF0YXIiOiIvL3d3dy5ncmF2YXRhci5jb20vYXZhdGFyLzQxMTkzY2RiZmZiZjA2YmUwY2RmMjMxYjI4YzU0YjE4P3M9MjAwJnI9cGcmZD1tbSIsImlhdCI6MTYzMDI0MjU4MywiZXhwIjoxNjMwMjQ2MTgzfQ.ZKwt9DaDqpyS__Jf0euZuc7pVClDIQA9FWBQdYwtNbM

### 1. Users
GET {{url}}/users/test HTTP/1.1
Content-type:application/json

###1. Get current user
GET  {{url}}/users/current HTTP/1.1
Content-Type:application/json
Authorization:Bearer {{player}}

### 1.Register new user
POST {{url}}/users/register HTTP/1.1
Content-Type:application/json

{
    "name":"John Doe",
    "email":"john@email.com",
    "password":"123456",
    "password2":"123456"

}


###1.Login user
POST {{url}}/users/login HTTP/1.1
Content-Type: application/json

{
    "email":"john@email.com",
    "password":"123456"
}



###2.Profile
GET {{url}}/profile/test HTTP/1.1
Content-type:application/json

###3.Posts
GET {{url}}/posts/test HTTP/1.1
Content-type:application/json